// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjU9OSK2Nhdr7bDHDQ1xeTtMFoitHv5w0',
    appId: '1:169841483553:web:ea1913ad6596cb39c4e860',
    messagingSenderId: '169841483553',
    projectId: 'high-five-f2b6a',
    authDomain: 'high-five-f2b6a.firebaseapp.com',
    storageBucket: 'high-five-f2b6a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOopZ8-Rl7OFjPZK4hEb1D8LFGXwxdt-I',
    appId: '1:169841483553:android:c66c3ce788b6078dc4e860',
    messagingSenderId: '169841483553',
    projectId: 'high-five-f2b6a',
    storageBucket: 'high-five-f2b6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOo8IVD0Fc9xQ_EoTxmikDvTr1WUVDCFA',
    appId: '1:169841483553:ios:707c2f675c13b38dc4e860',
    messagingSenderId: '169841483553',
    projectId: 'high-five-f2b6a',
    storageBucket: 'high-five-f2b6a.appspot.com',
    iosClientId: '169841483553-990mr9phfqhquttfhj0amapn3insko9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOo8IVD0Fc9xQ_EoTxmikDvTr1WUVDCFA',
    appId: '1:169841483553:ios:707c2f675c13b38dc4e860',
    messagingSenderId: '169841483553',
    projectId: 'high-five-f2b6a',
    storageBucket: 'high-five-f2b6a.appspot.com',
    iosClientId: '169841483553-990mr9phfqhquttfhj0amapn3insko9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatServices',
  );
}
